Error feedback
saga-vcs/saga-excel pull request #110
Opened 2020-06-08 04:20 UTC by aarondr77

# Changes

- [x] I ran all the tests to make sure I didn't break anything.

This creates a dialog box. Now, anytime there is an error, the user should be notified either through the dialog box or the taskpane.

2020-06-08 15:48 UTC, naterush requested changes
There is still some funky-ness around "starting in cell editing mode" (e.g. enter cell editing mode, click switch versions, it won't tell you to leave cell editing mode).

If I had to guess, I would say "being in cell editing mode" is gonna be more likely than "entering cell editing mode in the middle of an operation - but idk. In any case, let's either make changes here to improve the messaging or open an issue - and then merge.

2020-06-08 15:48 UTC, naterush commented on src/commands/commands.js
> +    console.log("manufal fix required");
delete or spell right

2020-06-08 15:48 UTC, naterush commented on src/notifications/errorDialog.html
> +        <p>An error occured while processing your request. Please try again.</p>
If I begin the operation while in cell editing mode, it gives me this error. The problem w/ that is that it tells me to retry w/out telling me to leave cell editing mode. 

Even though we don't have a safety commit in this case (e.g. begin switch version in cell editing mode), I feel like we should have messaging that is like "oh leave cell editing mode" if that is the case. Not sure of the best way to do that here...

Otherwise, this PR looks good to me.

2020-06-08 16:26 UTC, aarondr77 commented
@naterush I downloaded a spellchecker. That is all.

2020-06-10 23:40 UTC, aarondr77 commented
@naterush LGTM?

2020-06-11 03:32 UTC, naterush approved these changes
Cleaned up the error message (use headings and nice links!) -- but otherwise looks great.

2020-06-11 03:32 UTC, merged