Merge conflict fix
saga-vcs/saga-excel pull request #73
Opened 2020-05-25 20:00 UTC by aarondr77

# Changes

- [x] I ran all the tests to make sure I didn't break anything.

2020-05-25 20:08 UTC, naterush requested changes
Minor review for now. Will review in depth after changes.

2020-05-25 20:08 UTC, naterush commented on src/taskpane/components/MergeComponents/MergeConflictScreen.js
>      this.setState({default: isDefaultPersonal === "true" ? "your changes" : "your collaborator's changes"});
No more string comparison.

2020-05-25 20:08 UTC, naterush commented on src/tests/suites/mergeConflictsTests.js
> +    const updatedValue1A1= (await runOperation(getFormulas, "Sheet1", "A1"))[0][0];
Get the values in one operation and pick them off. Anything we do to not have horribly slow tests...

2020-05-25 20:08 UTC, naterush commented on src/tests/suites/mergeFormattingTests.js
> +        assert.equal(range.format.font.bold, true,  "A1 should be bold");
This assert needs to be outside the Excel.run

2020-05-25 20:08 UTC, naterush commented on src/tests/suites/mergeFormattingTests.js
> +    Excel.run(async function (context) {
You have to wait in the Excel.run to finish; it returns a promise.

2020-05-25 20:08 UTC, naterush commented on src/tests/suites/mergeFormattingTests.js
> +    Excel.run(async function (context) {
same here.

2020-05-25 20:08 UTC, naterush commented on src/tests/suites/mergeFormattingTests.js
> +    Excel.run(async function (context) {
and here

2020-05-25 20:13 UTC, aarondr77 commented
ooo shoot. I think when I rebased, I forgot to redo some of those fixes. Will do now.

2020-05-26 00:10 UTC, naterush approved these changes
This looks good to me. LGTM.

2020-05-26 00:10 UTC, naterush commented on src/tests/suites/mergeConflictsTests.js
> +    assert.equal(mergeConflictData[0].sheet, "Sheet2", "should contain conflicts on Sheet 2");
For now, this is fine, but it seems better to:
1. Make an object and do the comparison all at once
2. Have a test running that can helpfully display that error to you.

I'll open an issue now.

2020-05-26 00:10 UTC, merged