Error handling
saga-vcs/saga-excel pull request #99
Opened 2020-06-04 21:10 UTC by aarondr77

# Changes

Here you can see how I have started implementing the safety commit error handling. 

- [ ] I ran all the tests to make sure I didn't break anything.

2020-06-05 03:31 UTC, aarondr77 commented
TODO: handle the case where you edit cells before the safety commit occurs.

2020-06-05 05:58 UTC, naterush requested changes
Mostly minor changes requested here. The tests pass for me.

The only major question I have: do we still need to do another commit when you're checking out master from personal, if we already have a safety commit? It seems like in operations where we lead w/ a safety commit, we might as well just not do commits inside the operations themselves.

However, what do we do if we are calling the operation directly (rather than through the run operation interface?)

2020-06-05 05:58 UTC, naterush commented on src/taskpane/components/ErrorRevertScreen.js
> +        await runRevertToCommitAndBranch(this.props.safetyCommit, this.props.safetyBranch);
Nice code reuse.

2020-06-05 05:58 UTC, naterush commented on src/taskpane/components/ErrorRevertScreen.js
> +export default class ErrorRevertScreen extends React.Component {
Let's make this one of those function-components rather than a class.

2020-06-05 05:58 UTC, naterush commented on src/constants/index.js
> +    Returned by runOperationSafetyCommit to let add-in know if the operation was a success
It's not exactly what's returned by runOperationSafetyCommit. It's the status field returned by runOperationSafetyCommit -- quick comment update

2020-06-05 05:58 UTC, naterush commented on src/saga/Project.js
> +    Updates checked out branch item without checking out the branch
-> changes the branch saved in the saga sheet as checked out, without changing what sheets are visible.

2020-06-05 05:58 UTC, naterush commented on src/saga/checkout.js
> +    console.log("swtiching verisons");
no typo console logs allowed.

2020-06-05 05:58 UTC, naterush commented on src/saga/runOperation.js
> +                safetyCommit = await project.getCommitIDFromBranch("master");
Nice. So because we can't edit master, we can just get it's most recent commit as a safety commit.

2020-06-05 05:58 UTC, naterush commented on src/saga/runOperation.js
> +        if (error.debugInfo !== undefined) {
This can be better expressed as:
```
if (error.debugInfo && error.debugInfo.code === "InvalidOperationInCellEditMode") {
```

2020-06-05 05:58 UTC, naterush commented on src/saga/runOperation.js
> +                return;
You're not returning the result here, and also not turning syncing back on. I think just removing the return would fix this.

2020-06-05 05:58 UTC, naterush commented on src/saga/runOperation.js
> +    console.log("responding");
delete console log

2020-06-05 05:58 UTC, naterush commented on src/taskpane/components/ErrorRevertScreen.js
> +            <Taskpane header={headerSize.SMALL} title="Something went wrong while we were working on your request">
The title on this screen could be better - maybe we reference cell-editing mode specifically? Or just:

"You were editing a cell when we tried to do that."

2020-06-05 05:58 UTC, naterush commented on src/taskpane/components/ErrorRevertScreen.js
> +                    <p> 1. Make sure you're not in cell edditng mode. Hint: clicking on this text should do the trick!</p>
Some typos here

2020-06-05 05:58 UTC, naterush commented on src/taskpane/components/ErrorRevertScreen.js
> +                        <PrimaryButton className="reset-button" type="button" onClick={(e) => this.reset(e)}>Reset</PrimaryButton>
Let's not do it in this PR, but instead of just a reset, we could have a retry. We'd just had to save what operation was tried.

2020-06-05 05:58 UTC, naterush commented on src/taskpane/components/ErrorRevertScreen.js
> +                        <PrimaryButton className="reset-button" type="button" onClick={(e) => this.reset(e)}>Reset</PrimaryButton>
Opened an issue.

2020-06-05 15:00 UTC, aarondr77 commented on src/taskpane/components/ErrorRevertScreen.js
> +            <Taskpane header={headerSize.SMALL} title="Something went wrong while we were working on your request">
That's fair, but I was thinking this screen might be used for errors besides cell editing mode.

2020-06-06 04:55 UTC, aarondr77 commented
Let's learn from our previous product feedback and incorporate feedback into the error handling process. Right now, if we are able to revert to the old state we do so without notifying the user that their operation did not work properly. 

I think the taskpane is a clunky place to give this notification. Maybe we should look into creating a nice looking dialog box. Will address in a different PR. Opening an issue now.

2020-06-06 05:57 UTC, naterush requested changes
The error handling does not appear to be working for me. I (importantly) made sure I'm on the right branch (error-handling), and that I have the most up-to-date code pulled. 

1. If I open Excel, create a new Saga project, and then enter cell editing mode, and then click switch versions, no error screen appears (in fact, nothing changes at all). 
2. If I enter cell editing mode, and click merge, I get stuck on the merge loading screen permanently. 
3. If I enter cell editing mode, and then click catch up, the add-in crashes.

These bugs make me really think we shouldn't merge this w/out some testing. To test is a bit tricky, but I think you can do something like: create a workbook, make some change to it that will cause switch versions to error, and then run switch versions and make sure things are in the right state. E.g. to make switch versions error, you could delete the sheets on the head master commit.

2020-06-06 05:57 UTC, naterush commented on src/commands/commands.js
> +  if (! await (checkResultForError(result))) {
Check result for error is not an async promise and does not return a promise. You should not have to await on it.

2020-06-06 05:57 UTC, naterush commented on src/commands/commands.js
> +function checkResultForError(result) {
-> displayScreenIfError. Check usually doesn't change state, which this function does.

2020-06-06 05:57 UTC, naterush commented on src/saga/Project.js
> +    setCheckedOutBranch = async (headCommit) => {
Just so we have tests, let's write a really quick test for this one (should be easy).

2020-06-06 05:57 UTC, naterush commented on src/saga/merge.js
> -/*
sick deleting here :)

2020-06-06 05:57 UTC, naterush commented on src/saga/sagaUtils.js
> +    return runOperation(revertToCommitAndBranch, commit, branch);
Nope; remember: run operation is async, so you have to await on it. This is the same bug I just fixed in the other PR... keep your eyes peeled for when to use await and when to not!

2020-06-06 05:57 UTC, naterush commented on src/taskpane/components/ErrorRevertScreen.js
> +export default class ErrorRevertScreen extends React.Component {
This will cut out 15 lines of code or so, pretty cheaply. Worth doing IMO.

2020-06-06 05:57 UTC, naterush commented on src/taskpane/components/MergeComponents/MergeConflictResolutionErrorScreen.js
> +        return (
Typo here. Please make sure to proof read the screens themselves, this is a silly one to keep coming up.

2020-06-06 05:57 UTC, naterush commented on src/taskpane/components/MergeComponents/MergeConflictResolutionErrorScreen.js
> +                    <p> 1. Make sure you're not in cell edditng mode. Hint: clicking on this text should do the trick!</p>
Same typo here.

2020-06-06 23:04 UTC, naterush commented
I also tested errors in the middle of operations, and that's not working for me either. To replicate:
- Add a random throw statement (or a different error) in the middle of switchVersionFromRibbon function. 
- Run switch versions from ribbon. No error screen appears.

It also doesn't work for switch versions for cell editing mode, as far as I can tell. My most recent commit is `addressed github review` - just to make sure I'm on the right branch.

2020-06-07 06:07 UTC, naterush approved these changes
There are two main things left unfinished. 
1. First, we need to move to some notification if we need to rerun the operation (open an issue and tag it, if you please!).
2. Second, there's a bug w/ how merge is handeled, b/c we just stay in the merge in progress screen. Open an issue here too if you can. 

Otherwise, LGTM. I think we need to consider two things moving foward: 
1. How can we move everything "inside the app?" I'll open an issue about this, but it'll clean up our interface and cut out some code. 
2. Once we do (1), how can we handle errors in a "reacty-way" using error boundaries or whatever?

2020-06-07 06:07 UTC, naterush commented on src/commands/commands.js
>  function checkResultForError(result) {
Pushing for changing this function name. It's not checking something, it's displaying

2020-06-07 06:07 UTC, naterush commented on src/commands/commands.js
> +  // if the safetyCommit and safetyBranch are undefined, then we are in the correct state if the user deletes extra sheets
A bit more in the comment here. Why are we in the correct state? These can only be undefined if we error before the safety commit, right? In which case, it's like we've rolled back to the safety commit.

2020-06-07 06:07 UTC, naterush commented on src/commands/commands.js
> +  checkResultForError(result);
Opening an issue. We should have a screen if not an error, where it tells you what version you are on...

2020-06-07 06:07 UTC, naterush commented on src/saga/Project.js
> +    setCheckedOutBranch = async (headCommit) => {
bump a rump

2020-06-07 17:16 UTC, aarondr77 commented
Merged into dev

2020-06-07 17:16 UTC, closed without merging